name: Release
# If a version tag is pushed, this workflow will build the code and create a release draft

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - i686-unknown-linux-gnu
        - x86_64-pc-windows-gnu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Prepare cross-compiling
      if: matrix.target != 'x86_64-unknown-linux-gnu'
      run: |
        sudo apt update
        sudo apt -y install gcc-multilib
        rustup target add ${{ matrix.target }}
    - name: Install build dependency for windows
      if: matrix.target == 'x86_64-pc-windows-gnu'
      run: sudo apt -y install mingw-w64
    - run: cargo build --verbose --release --target ${{ matrix.target }}
    - name: Rename artifact
      run: mv target/${{ matrix.target }}/release/${{ github.event.repository.name }} ${{ github.event.repository.name }}-${{ matrix.target }}
    - uses: actions/upload-artifact@v3
      with:
        path: ${{ github.event.repository.name }}-${{ matrix.target }}
        retention-days: 1
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create --draft --prerelease --title ${GITHUB_REF#refs/*/} ${{ github.ref }} artifact/*
