name: Release
# If a version tag is pushed, this workflow will build the code and create a release draft

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - i686-pc-windows-gnu
    runs-on: ubuntu-latest
    name: Build ${{ matrix.target }}
    env:
      binary_ext: ${{ matrix.target == 'x86_64-pc-windows-gnu' && '.exe' || matrix.target == 'i686-pc-windows-gnu' && '.exe' || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@master

      - name: Install cross-compilation dependencies
        if: matrix.target != 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt update
          sudo apt -y install gcc-multilib
          rustup target add ${{ matrix.target }}

      - name: Install Windows dependencies
        if: matrix.target == 'x86_64-pc-windows-gnu' || matrix.target == 'i686-pc-windows-gnu'
        run: sudo apt -y install mingw-w64

      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Rename artifact
        run: mv target/${{ matrix.target }}/release/${{ github.event.repository.name }}${{ env.binary_ext }} ${{ github.event.repository.name }}-${{ matrix.target }}${{ env.binary_ext }}

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target }}${{ env.binary_ext }}
          path: ${{ github.event.repository.name }}-${{ matrix.target }}${{ env.binary_ext }}
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    name: Draft release
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Download artifacts
        uses: actions/download-artifact@main
        with:
          path: artifact
          merge-multiple: true

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create --draft --prerelease --title ${GITHUB_REF#refs/*/} ${{ github.ref }} artifact/*
