name: Test

on:
  push:
    branches: [ "main" ]
    paths: [ "src/**", "Cargo.toml" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Test
      run: cargo test --verbose
