name: Version Tag
# If the version in Cargo.toml is changed, this workflow will create a new tag

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Cargo.toml'

permissions:
  contents: write

jobs:
  version-tag:
    runs-on: ubuntu-latest
    name: Create version tag
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Read version from Cargo.toml
        id: read-version
        run: echo "version=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == \"minicrust\") | .version')" >> "$GITHUB_OUTPUT"

      - name: Create tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "v${{ steps.read-version.outputs.version }}" || true
          git push --tags || true
